### ISSUE TITLE
symfony/serializer 未安装，但是引用了

### ISSUE THREAD

**Issue by silence-ice** [tw2066/dto#7]
包里面 ObjectDtoNormalizer.php 类使用 symfony/serializer 包里面的东西，但是未安装该包，需要 composer require symfony/serializer

<img width="771" alt="image" src="https://github.com/tw2066/dto/assets/14326910/08603cbe-06d0-479b-b74e-dfec00b6955f">

**Comment by tw2066** [comment]
已引入
