### ISSUE TITLE
关于CoreMiddlewareAspect类的问题

### ISSUE THREAD

**Issue by imlinfly** [tw2066/dto#8]
CoreMiddlewareAspect::transferToResponse方法中调用的ResponseInterface::addHeader方法好像未定义
最新的psr http-message 是使用withHeader设置的header

```php
Error: Call to undefined method Hyperf\HttpMessage\Server\Response::addHeader() 
in /project/vendor/tangwei/dto/src/Aspect/CoreMiddlewareAspect.php:81
```
![image](https://github.com/tw2066/dto/assets/45063822/60de3430-dfbe-4398-9b62-33ae95f914e0)
![image](https://github.com/tw2066/dto/assets/45063822/38a4bebf-e055-473e-afd9-6153f2b57e19)

**Comment by tw2066** [comment]
69b7f21524d567d4b628f2d4a1526ebc75d60441
